name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: YOUR_SERVER_IP
          username: deployuser
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /home/deployuser/YOUR_REPOSITORY
            git pull origin main
            echo "Deployment completed!"
